name: build

on:
  workflow_dispatch: {}

env:
  CARGO_INCREMENTAL: 0
  # removed: impl warning turns into error: RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    name: Build
    strategy:
      matrix:
        toolchain:
          - stable
          - 1.74.0 # MSRV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rust-${{ matrix.toolchain }}-cargo-build-target-${{ hashFiles('Cargo.lock') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Install libudev-dev
        run: sudo apt-get update && sudo apt-get install libudev-dev

      - name: Build with fortanix and debian
        run: |
          cargo install cargo-deb
          cargo build --features=softsign,fortanixdsm --release
          cargo deb --profile release -- --features fortanixdsm,softsign